version: '3'
services:
  app:
    image: star-wars-planets:local
    container_name: star-wars-planet
    network_mode: host
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    container_name: mongodb
    network_mode: host
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
  redis:
    image: redis
    command: redis-server
    network_mode: host
    ports:
      - "6379:6379"
volumes:
  data-volume: