version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
volumes:
  data-volume: